#
# make the MPAR library (functions to determine machine constants)
#
# NOTE:
#        must be compiled with either -ffloat-store
#        or without optimization.
#

FF = gfortran
FFLAGS = -O -ffloat-store

F = i1mach.f spmpar.f dpmpar.f r1mach.f d1mach.f smachar.f dmachar.f

O = $(F:.f=.o)

libMPAR.a : $(O)
	ar rv libMPAR.a $?
	ranlib libMPAR.a

clean :
	rm -f *~*~ *.o libMPAR.a

install :
	install -m 644 -o root -g root libMPAR.a /usr/local/lib

%.o : %.f
	$(FF) -c $(FFLAGS) $<
