#
# makefile for libCommon
#

CC = gcc
CFLAGS = -g -fomit-frame-pointer -DHAVE_ANSI_TIME -I.

C = List.c byteorder.c timer.c regexpr.c fits_io.c

O = $(C:.c=.o)

libCommon.a: $(O)
	ar rv libCommon.a $?
	ranlib libCommon.a

%.o : %.c
	$(CC) -c $(CFLAGS) $<

clean:
	rm -f *.o *~*~ libCommon.a

